import assert from "node:assert/strict";
import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const testDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(testDirectory, "..");

async function loadHarness() {
  const source = String.raw`
    import {
      LocalCodexProvider,
      isCurrentCourseItemReady,
    } from "./app/providers/local-codex.ts";
    import { TUTOR_PROTOCOL_VERSION } from "./app/protocol/index.ts";

    const statement =
      "Let $\\alpha$ be algebraic over $K$ with minimal polynomial $m_\\alpha$. Then evaluation induces an isomorphism $K[x]/(m_\\alpha)\\cong K(\\alpha)$.";
    const kernelStep =
      "Consider the evaluation homomorphism $\\varphi:K[x]\\to K(\\alpha)$, $f\\mapsto f(\\alpha)$. Its kernel is $(m_\\alpha)$.";
    const completionStep =
      "Its image is $K[\\alpha]=K(\\alpha)$ because $\\alpha$ is algebraic. The first isomorphism theorem now gives $K[x]/(m_\\alpha)\\cong K(\\alpha)$.";

    const lesson = {
      schemaVersion: 1,
      contentVersion: 1,
      id: "progressive-proposition-test",
      title: "Progressive proposition test",
      contentFormat: "markdown-with-math",
      documentMode: "course-notes",
      settings: {
        schemaVersion: 1,
        profile: {
          id: "course-guide",
          name: "Course guide",
          personality: "Quiet and precise.",
          customPrompts: [],
        },
        studentBackgroundPrompt: "The student knows group theory and linear algebra.",
        curriculum: [{
          id: "simple-extension-quotient",
          kind: "proposition",
          title: "Simple extensions as polynomial quotients",
        }],
      },
      roadmap: [{ statementId: "simple-extension-quotient" }],
      targetStatementId: "simple-extension-quotient",
      initialStepId: "course-start",
      steps: {
        "course-start": {
          id: "course-start",
          mode: "orientation",
          focusStatementId: "simple-extension-quotient",
          entryMessages: [],
          hint: "Develop the proposition.",
        },
      },
      proof: {
        documentTitle: "Course notes",
        preamble: [
          "\\documentclass{article}",
          "\\usepackage{amsmath,amssymb,amsthm}",
          "\\newtheorem{proposition}{Proposition}",
          "\\begin{document}",
        ].join("\\n"),
        opening: "",
        fragments: {},
        closing: "\\end{document}",
      },
    };

    function response(request, commands, intent) {
      return {
        protocolVersion: TUTOR_PROTOCOL_VERSION,
        requestId: request.requestId,
        classification: {
          type: "classify_student_intent",
          intent,
          confidence: 1,
          rationale: "Deterministic progressive-note fixture.",
        },
        commands,
      };
    }

    function progress(request, proofFragmentLatex, complete) {
      return response(request, [{
        type: "record_course_note_progress",
        statementId: "simple-extension-quotient",
        latex: statement,
        ...(proofFragmentLatex ? { proofFragmentLatex } : {}),
        complete,
        reason: "The conversation established this mathematics.",
      }], proofFragmentLatex ? "proof_step" : "proposed_approach");
    }

    function occurrences(source, fragment) {
      return source.split(fragment).length - 1;
    }

    export async function exerciseProgressiveProposition() {
      let turn = 0;
      const provider = new LocalCodexProvider(async (request) => {
        if (request.studentInput.kind === "session_start") {
          return response(request, [{
            type: "reply",
            markdown: "Let us formulate the proposition precisely.",
          }], "session_start");
        }
        turn += 1;
        if (turn === 1) return progress(request, undefined, false);
        if (turn === 2) return progress(request, kernelStep, false);
        return progress(request, completionStep, true);
      });

      const started = await provider.createSession(lesson);
      const established = await provider.dispatch(lesson, started.state, {
        type: "message",
        text: "Evaluation should identify the simple extension with a polynomial quotient.",
      });
      const afterKernel = await provider.dispatch(lesson, established.state, {
        type: "message",
        text: "The kernel of evaluation is the annihilator ideal generated by the minimal polynomial.",
      });
      const completed = await provider.dispatch(lesson, afterKernel.state, {
        type: "message",
        text: "The image is the whole simple extension, so the first isomorphism theorem finishes the proof.",
      });

      const summarize = (result) => ({
        accepted: result.accepted,
        entry: result.state.proof.courseNoteEntries?.[0],
        writtenIds: result.state.proof.courseNoteStatementIds ?? [],
        ready: isCurrentCourseItemReady(lesson, result.state),
        editorHasStatement: result.state.proof.editorLatex.includes(statement),
        previewHasStatement: result.state.proof.previewLatex.includes(statement),
        editorKernelCount: occurrences(result.state.proof.editorLatex, kernelStep),
        previewKernelCount: occurrences(result.state.proof.previewLatex, kernelStep),
        editorCompletionCount: occurrences(
          result.state.proof.editorLatex,
          completionStep,
        ),
        previewCompletionCount: occurrences(
          result.state.proof.previewLatex,
          completionStep,
        ),
      });

      return {
        statement,
        kernelStep,
        completionStep,
        established: summarize(established),
        afterKernel: summarize(afterKernel),
        completed: summarize(completed),
      };
    }
  `;

  const result = await build({
    stdin: {
      contents: source,
      resolveDir: projectRoot,
      sourcefile: "progressive-course-note-provider-harness.ts",
      loader: "ts",
    },
    bundle: true,
    format: "esm",
    platform: "node",
    write: false,
    external: ["react", "react-dom", "react-dom/*"],
  });
  const encoded = Buffer.from(result.outputFiles[0].text).toString("base64");
  return import(`data:text/javascript;base64,${encoded}`);
}

test("a proposition statement and accepted proof steps are recorded progressively", async () => {
  const harness = await loadHarness();
  const result = await harness.exerciseProgressiveProposition();

  assert.equal(result.established.accepted, true);
  assert.deepEqual(result.established.entry, {
    statementId: "simple-extension-quotient",
    latex: result.statement,
    complete: false,
  });
  assert.equal(result.established.editorHasStatement, true);
  assert.equal(result.established.previewHasStatement, true);
  assert.deepEqual(result.established.writtenIds, []);
  assert.equal(result.established.ready, false);

  assert.equal(result.afterKernel.accepted, true);
  assert.equal(result.afterKernel.entry.proofLatex, result.kernelStep);
  assert.equal(result.afterKernel.entry.complete, false);
  assert.equal(result.afterKernel.editorKernelCount, 1);
  assert.equal(result.afterKernel.previewKernelCount, 1);
  assert.deepEqual(result.afterKernel.writtenIds, []);
  assert.equal(result.afterKernel.ready, false);

  assert.equal(result.completed.accepted, true);
  assert.equal(
    result.completed.entry.proofLatex,
    `${result.kernelStep}\n\n${result.completionStep}`,
  );
  assert.equal(result.completed.entry.complete, true);
  assert.equal(result.completed.editorKernelCount, 1);
  assert.equal(result.completed.previewKernelCount, 1);
  assert.equal(result.completed.editorCompletionCount, 1);
  assert.equal(result.completed.previewCompletionCount, 1);
  assert.deepEqual(result.completed.writtenIds, ["simple-extension-quotient"]);
  assert.equal(result.completed.ready, true);
});
